### ISSUE TITLE
Make Xpub Scan more easily configurable

### ISSUE THREAD

**Issue by glethuillier-ledger** [LedgerHQ/xpub-scan#14]
The configuration options are set in `src/settings.ts`.

Therefore, each time an end-user configures the tool, it has to be rebuilt. 

A more user-friendly approach could be to make it a JSON (or, preferably, a YAML) file automatically parsed (and validated) when the user runs the tool.

**Comment by twilgenbus-ledger** [comment]
I think you've recently added the library dot-env to the project? Using the .env could also be a clean way to set this configuration.

**Comment by glethuillier** [comment]
@twilgenbus-ledger That could be a great idea indeed. Note that we also need to provide a default configuration: the tool should be operational even without any `.env`.
